// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/16/2026, 5:55:05 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Cole/Documents/GitHub/united-printing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Cole/Documents/GitHub/united-printing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Cole/Documents/GitHub/united-printing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Cole/Documents/GitHub/united-printing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Cole/Documents/GitHub/united-printing/plugins/**/*.{js,ts,mjs}","C:/Users/Cole/Documents/GitHub/united-printing/composables/**/*.{js,ts,mjs}","C:/Users/Cole/Documents/GitHub/united-printing/utils/**/*.{js,ts,mjs}","C:/Users/Cole/Documents/GitHub/united-printing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Cole/Documents/GitHub/united-printing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Cole/Documents/GitHub/united-printing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Cole/Documents/GitHub/united-printing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;